obj-$(CONFIG_VIDEO_T4K35_180) += t4k35_180.o

t4k35_180-objs := tsb.o dw9714.o otp_t4k35.o

ccflags-y += -Werror

# leong++  change to clovertrail ISP( \include\linux\atomisp_css15.h )
ccflags-y += -DCSS15
